### ISSUE TITLE
https://api.mainnet.minepi.com/operations/57720890124673025

### ISSUE THREAD

**Issue by pannu5788** [Uniswap/UniswapX#230]
{
  "_links": {
    "self": {
      "href": "https://api.mainnet.minepi.com/operations/57720890124673025"
    },
    "transaction": {
      "href": "https://api.mainnet.minepi.com/transactions/dd5121380a88ba1269eb427347187e3aa050b832f08322381b453cd7a9205632"
    },
    "effects": {
      "href": "https://api.mainnet.minepi.com/operations/57720890124673025/effects"
    },
    "succeeds": {
      "href": "https://api.mainnet.minepi.com/effects?order=desc\u0026cursor=57720890124673025"
    },
    "precedes": {
      "href": "https://api.mainnet.minepi.com/effects?order=asc\u0026cursor=57720890124673025"
    }
  },
  "id": "57720890124673025",
  "paging_token": "57720890124673025",
  "transaction_successful": true,
  "source_account": "GDZAIZDOJ3RB5Q6VB2HRCOGTJJKHNNSTAV7SLFB67Y5ZF72DX2XE74UW",
  "type": "claim_claimable_balance",
  "type_i": 15,
  "created_at": "2024-02-28T07:32:33Z",
  "transaction_hash": "dd5121380a88ba1269eb427347187e3aa050b832f08322381b453cd7a9205632",
  "balance_id": "0000000009a0c52572f2e9a37b5277aabd07ec5442d41b4f771948a681a9723d950b940a",
  "claimant": "GDZAIZDOJ3RB5Q6VB2HRCOGTJJKHNNSTAV7SLFB67Y5ZF72DX2XE74UW"
}

**Comment by bujval167** [comment]
> { "_links": { "self": { "href": "https://api.mainnet.minepi.com/operations/57720890124673025" }, "transaction": { "href": "https://api.mainnet.minepi.com/transactions/dd5121380a88ba1269eb427347187e3aa050b832f08322381b453cd7a9205632" }, "effects": { "href": "https://api.mainnet.minepi.com/operations/57720890124673025/effects" }, "succeeds": { "href": "[https://api.mainnet.minepi.com/effects?order=desc\u0026cursor=57720890124673025](https://api.mainnet.minepi.com/effects?order=desc%5Cu0026cursor=57720890124673025)" }, "precedes": { "href": "[https://api.mainnet.minepi.com/effects?order=asc\u0026cursor=57720890124673025](https://api.mainnet.minepi.com/effects?order=asc%5Cu0026cursor=57720890124673025)" } }, "id": "57720890124673025", "paging_token": "57720890124673025", "transaction_successful": true, "source_account": "GDZAIZDOJ3RB5Q6VB2HRCOGTJJKHNNSTAV7SLFB67Y5ZF72DX2XE74UW", "type": "claim_claimable_balance", "type_i": 15, "created_at": "2024-02-28T07:32:33Z", "transaction_hash": "dd5121380a88ba1269eb427347187e3aa050b832f08322381b453cd7a9205632", "balance_id": "0000000009a0c52572f2e9a37b5277aabd07ec5442d41b4f771948a681a9723d950b940a", "claimant": "GDZAIZDOJ3RB5Q6VB2HRCOGTJJKHNNSTAV7SLFB67Y5ZF72DX2XE74UW" }

**Comment by draghtnight** [comment]
> {
>   "_links": {
>     "self": {
>       "href": "https://api.mainnet.minepi.com/operations/57720890124673025"
>     },
>     "transaction": {
>       "href": "https://api.mainnet.minepi.com/transactions/dd5121380a88ba1269eb427347187e3aa050b832f08322381b453cd7a9205632"
>     },
>     "effects": {
>       "href": "https://api.mainnet.minepi.com/operations/57720890124673025/effects"
>     },
>     "succeeds": {
>       "href": "https://api.mainnet.minepi.com/effects?order=desc\u0026cursor=57720890124673025"
>     },
>     "precedes": {
>       "href": "https://api.mainnet.minepi.com/effects?order=asc\u0026cursor=57720890124673025"
>     }
>   },
>   "id": "57720890124673025",
>   "paging_token": "57720890124673025",
>   "transaction_successful": true,
>   "source_account": "GDZAIZDOJ3RB5Q6VB2HRCOGTJJKHNNSTAV7SLFB67Y5ZF72DX2XE74UW",
>   "type": "claim_claimable_balance",
>   "type_i": 15,
>   "created_at": "2024-02-28T07:32:33Z",
>   "transaction_hash": "dd5121380a88ba1269eb427347187e3aa050b832f08322381b453cd7a9205632",
>   "balance_id": "0000000009a0c52572f2e9a37b5277aabd07ec5442d41b4f771948a681a9723d950b940a",
>   "claimant": "GDZAIZDOJ3RB5Q6VB2HRCOGTJJKHNNSTAV7SLFB67Y5ZF72DX2XE74UW"
> }
